In [2]:
result1 = 0  # 2, 5 , 7
def add1(num):
    global result1
    result1 = result1 + num

In [4]:
add1(2)
print(result1)

2


In [5]:
add1(5)
print(result1)

7


In [6]:
result2 = 0
def add2(num):
    global result2
    result2 = result2 + num

In [7]:
add2(4)
print(result2)

4


In [8]:
print(result1)

7


In [9]:
class Calculator:
    result = 0
    def add(self, num):
        self.result = self.result + num
        
    # cal1.add(2) => Calculator.add(cal1, 2)

In [27]:
cal1.add(2)
print(cal1.result)

8


In [29]:
Calculator.add(cal1, 2)
print(cal1.result)

12


In [11]:
cal1 = Calculator() # result, add()
cal1.add(2)
print(cal1.result)

2


In [12]:
cal1.add(4)
print(cal1.result)

6


In [13]:
cal2 = Calculator()
cal2.add(4)
print(cal2.result)

4


In [33]:
# 메버필드에 값을 초기화 시키기
class FourCal:
    def setdata(self, first,second):
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
        return self.result
    def sub(self):
        self.result = self.first - self.second
        return self.result
    def mul(self):
        self.result = self.first * self.second
        return self.result
    def div(self):
        self.result = self.first / self.second
        return self.result

In [17]:
a = FourCal()
a.setdata(5 , 2)

In [18]:
b = a.add()
print(b)

7


In [19]:
b = a.sub()
print(b)

3


In [21]:
c = FourCal()

In [23]:
FourCal.setdata(c, 4, 2)  #  c.setdata(4, 2)

In [24]:
print(c.add())

6


In [25]:
print(FourCal.sub(c))

2


In [32]:
 class FourCal1:
    def __init__(self, first,second): # 생성자 : 멤버변수를 초기화
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
        return self.result
    def sub(self):
        self.result = self.first - self.second
        return self.result
    def mul(self):
        self.result = self.first * self.second
        return self.result
    def div(self):
        self.result = self.first / self.second
        return self.result

In [37]:
b = FourCal1(4, 2)  # __init__()자동으로 실행이 됨

In [38]:
print(b.first)
print(b.second)

4
2


In [71]:
class FourCal2:
    def __init__(self, first,second): # 생성자 : 멤버변수를 초기화
        self.first = first
        self.second = second
    def mul(self):
        result = self.first * self.second
        return result
    def div(self):
        result = self.first / self.second
        return result 

In [83]:
class MoreFourCal(FourCal2):
    def add(self):
        result = self.first + self.second
        return result
    def sub(self):
        result = self.first - self.second
        return result
    def div(self): ### 오버라이딩 : 재정의
        if self.second == 0:
            result = 0
        else: 
            result = self.first / self.second
        return result
    

In [73]:
e = MoreFourCal(4, 2)
print(e.add())
print(e.mul())

6
8


In [84]:
eee = MoreFourCal(8 , 0)

In [85]:
print(eee.add())
print(eee.sub())
print(eee.mul())
print(eee.div()) # 8 / 0 : 불능     0 /3 = 0 부정

8
8
0
0


In [1]:
import mod1

In [3]:
aaa = mod1.FourCal12()

In [4]:
aaa.setdata(4, 2)
print(aaa.add())

6


In [5]:
print(mod1.PI)

3.141592


In [9]:
print(mod1.add12(2,5))

7


In [18]:
from mod2 import *

In [11]:
dddd = FourCal34()

In [20]:
dddd.setdata(3, 4)
dddd.add()

7

In [19]:
print(PI)

3.14


In [16]:
# numpy (Numerical Python)
# pandas 
# matplotlib (시각화)
import numpy as np
num = np.random.randint(10)
print(num)

1


In [18]:
#### 숫자로 이루어져 있는 1차원 배열, 2차원 배열 , 다차원배열
num = np.random.randint(10, size=6)
print(num)
l = [1,2,3,4,5,6]
print(l)

[8 2 7 2 4 3]
[1, 2, 3, 4, 5, 6]


In [19]:
num2 = np.random.randint(10, size=(3, 4))
print(num2)

[[6 8 3 9]
 [7 4 6 9]
 [5 5 4 4]]


In [25]:
print(num) # 배열
print(l)   # 리스트
print(l[3])
print(num[3])
print(l[-1])
print(num[-1])
print(l[-2])
print(num[-2])

[8 2 7 2 4 3]
[1, 2, 3, 4, 5, 6]
4
2
6
3
5
4


In [36]:
print(num2)
l2 = [[6, 8, 3, 9],[7, 4, 6, 9], [5, 5, 4, 4]]
##        0 , -3      1 , -2         2,-1
##     0  1   2  3  0  1   2  3   0  1  2  3
print(l2)
print(l2[1][2])
### print(l2[1 ,2])
print(num2[1][2]) # 리스트 표현식
print(num2[1, 2]) # 배열 표현식 
print(l2[-2][2])
print(num2[-2][2])
print(num2[-2 , 2])

[[6 8 3 9]
 [7 4 6 9]
 [5 5 4 4]]
[[6, 8, 3, 9], [7, 4, 6, 9], [5, 5, 4, 4]]
6
6
6
6
6
6


In [38]:
print(l)
print(num)
l[2] = 15
num[2] = 15
print(l)
print(num)

[1, 2, 3, 4, 5, 6]
[8 2 7 2 4 3]
[1, 2, 15, 4, 5, 6]
[ 8  2 15  2  4  3]


In [46]:
print(l)
print(num)
print(l[0:5])
print(num[0:5])
print(l[0:5:2]) 
print(num[0:5:2])
print(l[:5])
print(num[:5])
print(l[2:])
print(num[2:])
print(l[::-1])
print(num[::-1])

[1, 2, 15, 4, 5, 6]
[ 8  2 15  2  4  3]
[1, 2, 15, 4, 5]
[ 8  2 15  2  4]
[1, 15, 5]
[ 8 15  4]
[1, 2, 15, 4, 5]
[ 8  2 15  2  4]
[15, 4, 5, 6]
[15  2  4  3]
[6, 5, 4, 15, 2, 1]
[ 3  4  2 15  2  8]
[13  7 20  7  9  8]


In [48]:
print(l)
print(num)
l[2] = 3.141592
num[2] = 3.141592
print(l)
print(num)

[1, 2, 15, 4, 5, 6]
[ 8  2 15  2  4  3]
[1, 2, 3.141592, 4, 5, 6]
[8 2 3 2 4 3]


In [67]:
print(l2)
print(num2)
#[[6, 8, 3, 9], [7, 4, 6, 9], [5, 5, 4, 4]]
#       0             1            2
#  0  1   2  3    0  1  2  3   0  1  2  3

# [[6 8 3 9]      0
#  [7 4 6 9]      1
#  [5 5 4 4]]     2
#   0 1 2 3
print(l2[1][1:3])
print(num2[1][1:3])
print(l2[0:2])
print(l2[0:2][0:2])
print(num2[0:2])
print(num2[0:2][0:2])
print(num2[0:2 , 0:2]) # 배열 표현식
### 열을 한칸씩 건너 띄우기
print(num2[: , ::2])
### 행을 한칸씩 건너 띄우기
print(num2[::2, :])
### 행:열을 한칸씩 건너 띄우기
print(num2[::2, ::2])

[[6, 8, 3, 9], [7, 4, 6, 9], [5, 5, 4, 4]]
[[6 8 3 9]
 [7 4 6 9]
 [5 5 4 4]]
[4, 6]
[4 6]
[[6, 8, 3, 9], [7, 4, 6, 9]]
[[6, 8, 3, 9], [7, 4, 6, 9]]
[[6 8 3 9]
 [7 4 6 9]]
[[6 8 3 9]
 [7 4 6 9]]
[[6 8]
 [7 4]]
[[6 3]
 [7 6]
 [5 4]]
[[6 8 3 9]
 [5 5 4 4]]
[[6 3]
 [5 4]]


In [76]:
print(num2)
print(num2[::-1]) # 행을 뒤집어 출력
print(num2[: , ::-1]) # 열을 뒤집어
print(num2[::-1, ::-1]) # 행과열을 뒤집어 출력
### 첫번째 행만 출력
print(num2[0])
print(num2[0 , :])
### 첫번째 열만 출력
print(num2[:, 0])

### num2에서 1행 1열의 값을 99로 변경하시오.
num2[0,0] = 99
print(num2)
print(np.transpose(num2))

[[99  8  3  9]
 [ 7  4  6  9]
 [ 5  5  4  4]]
[[ 5  5  4  4]
 [ 7  4  6  9]
 [99  8  3  9]]
[[ 9  3  8 99]
 [ 9  6  4  7]
 [ 4  4  5  5]]
[[ 4  4  5  5]
 [ 9  6  4  7]
 [ 9  3  8 99]]
[99  8  3  9]
[99  8  3  9]
[99  7  5]
[[99  8  3  9]
 [ 7  4  6  9]
 [ 5  5  4  4]]
[[99  7  5]
 [ 8  4  5]
 [ 3  6  4]
 [ 9  9  4]]


In [83]:
i = np.arange(9).reshape(3,3)# 0~8의 3행 3열
print(i)
#j = np.arange(9).reshape(3,4) # 수의 갯수와 배열의 크기가 일치하지 않으면 오류
j = np.arange(12).reshape(3,4)
print(j)
i = np.arange(11,20).reshape(3,3)
print(i)
i = np.arange(1,4).reshape(3,1)
print(i)
i = np.arange(1,4).reshape(3)
print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1]
 [2]
 [3]]
[1 2 3]


In [92]:
ii = np.array([1,2,3])
print(ii)
jj = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(jj)
kk = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(kk)
print(kk[0,0,0])
mm = np.array([
    [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],
    [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
])
print(mm[0,0,0,0])

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
1


In [96]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(x)
print(y)
z = np.concatenate([x,y])
print(z)
v = [99,99,99]
z  = np.concatenate([x,y,v])
print(z)

[1 2 3]
[3 2 1]
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]


In [101]:
x1 = np.array([[1, 2, 3],[4,5,6]])
y1 = np.array([[7, 8, 9],[10,11,12]])
z1 = np.concatenate([x1,y1])
print(z1) 
z1 = np.concatenate([x1,y1],axis=1) # y 축기준 : 열에 붙음
print(z1)
z1 = np.concatenate([x1,y1],axis=0) # x 축기준 : 행으로 붙음
print(z1)
# z1 = np.concatenate([x1,y1],axis=2) # z축기준 :3차원인 경우

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [106]:
x2 = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
        [6, 5, 4]])
# z = np.concatenate([x2 ,grid]) #차원이 다른 경우에는 사용하지 못함
z = np.vstack([x2 ,grid]) # x축기준으로 합침 : 열의 크기가가 다르면 안됨
print(z)
z = np.vstack([grid, x2])
print(z)
y2 = np.array([[1],[2]])
z = np.hstack([y2 ,grid]) # x축기준으로 합침 : 행의크기가 다르면 안됨
print(z)
z = np.hstack([grid, y2]) # x축기준으로 합침 : 행의크기가 다르면 안됨
print(z)


[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [1 2 3]]
[[1 9 8 7]
 [2 6 5 4]]
[[9 8 7 1]
 [6 5 4 2]]


In [117]:
# 유니버설 함수(UFuncs)
x = np.arange(4)
print(x)
y = np.add(x, 5)
print(y)
y = np.subtract(x, 5)
print(y)
y = np.multiply(x, 5)
print(y)

y = x + 5
print(y)
y = x - 5
print(y)
y = x * 5
print(y)
y = np.floor_divide(x, 5)
print(y)
y = x // 5
print(y)
y = x ** 5
print(y)

'''
l = [1,2,3]
print( l + 5)
'''

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0 0 0 0]
[0 0 0 0]
[  0   1  32 243]


TypeError: can only concatenate list (not "int") to list

In [116]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
c = a + b
print(c)
d = a + 5
print(d)

[5 6 7]
[5 6 7]


In [119]:
a = np.arange(3) # y축기준 [0, 1, 2] 
b = np.arange(3)[:,np.newaxis] # x축 [0]
                               #     [1]
                               #     [2]
print(a)
print(b)
c = a + b 
print(c)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [123]:
M = np.ones((3,3))
print(M)
print(a)
c = M + a
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [3]:
import numpy as np
import pandas as pd
rainfall = pd.read_csv('https://raw.githubusercontent.com/SoongMoo/soldesk202108/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/Seattle2014.csv')
#print(rainfall)
nprain = rainfall['PRCP']
#print(nprain)
nprain = np.array(nprain) # series를  np배열 변환
#print(nprain)
inches = nprain / 254
#print(inches)

import matplotlib.pyplot as plt
import seaborn; 
seaborn.set()
plt.hist(inches, 40)
plt.title("Seattle2014")
plt.xlabel("PRCP")
plt.ylabel("day")

Text(35.75, 0.5, 'day')

In [4]:
l = [1,2,3,4] # l + 5
print(l)
idx = 0
while True:
    l[idx] = l[idx] + 5
    if idx == len(l) - 1:
        break
    idx += 1
print(l)

[1, 2, 3, 4]
[6, 7, 8, 9]


In [11]:
# 배열 분할하기
x = np.array([1, 2, 3, 99, 99, 3, 2, 1,3])
x1 , x2 , x3 = np.split(x, 3)
print(x1)
print(x2)
print(x3)

x = np.array([1, 2, 3, 99, 99, 3, 2, 1,3])
x1 , x2 , x3, x4 = np.split(x, [3,5,7])
print(x1)
print(x2)
print(x3)
print(x4)

[1 2 3]
[99 99  3]
[2 1 3]
[1 2 3]
[99 99]
[3 2]
[1 3]


In [14]:
grid = np.arange(16).reshape((4, 4))
print(grid)
y1 , y2 = np.vsplit(grid,[2])
print(y1)
print(y2)
y1 , y2 = np.hsplit(grid,[2])
print(y1)
print(y2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [22]:
x = np.random.rand(1000000)
print(x)
y = sum(x)
print(y)
z = np.sum(x)
print(z)
%timeit sum(x)
%timeit np.sum(x)

[0.29276169 0.51947305 0.59120468 ... 0.07319718 0.99949219 0.22425308]
499917.4134744699
499917.413474474
94.1 ms ± 4.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.63 ms ± 448 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
M = np.random.random((3, 4))
print(M)
print(M.sum())
print(M.min())
### 열에서 최소값
print(M.min(axis=0))
### 행에 대한 최소값
print(M.min(axis=1))

[[0.75847934 0.04690553 0.4430911  0.03760998]
 [0.31571602 0.61684881 0.44197317 0.39589787]
 [0.27172359 0.84596332 0.45340615 0.28564247]]
4.913257349123676
0.037609975454884315
[0.27172359 0.04690553 0.44197317 0.03760998]
[0.03760998 0.31571602 0.27172359]


In [38]:
data = pd.read_csv('https://raw.githubusercontent.com/SoongMoo/soldesk202108/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)
print(heights.mean()) # 평균값
print(heights.min()) # 최소값    0 사분위
print(heights.max()) # 최대값    4  사분위
print(heights.std()) # 표준편차
# print(heights.median())
print(np.median(heights)) # 중앙값  2사분위
print(np.percentile(heights, 25)) # 1 사분위 25%
print(np.percentile(heights, 75)) # 3 사분위 75%

plt.hist(heights)
plt.title("미국 대통령의 키 분포")
plt.xlabel("height(cm)")
plt.ylabel("number")

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
179.73809523809524
163
193
6.931843442745892
182.0
174.25
183.0


Text(35.75, 0.5, 'number')

C:\Users\soldesk\.conda\envs\python503\lib\site-packages\matplotlib\backends\backend_agg.py:240: RuntimeWarning: Glyph 48120 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\soldesk\.conda\envs\python503\lib\site-packages\matplotlib\backends\backend_agg.py:240: RuntimeWarning: Glyph 44397 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\soldesk\.conda\envs\python503\lib\site-packages\matplotlib\backends\backend_agg.py:240: RuntimeWarning: Glyph 45824 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\soldesk\.conda\envs\python503\lib\site-packages\matplotlib\backends\backend_agg.py:240: RuntimeWarning: Glyph 53685 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\soldesk\.conda\envs\python503\lib\site-packages\matplotlib\backends\backend_agg.py:240: RuntimeWarning: Glyph 47161 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\soldesk\.conda\envs\python503\lib\site-package

In [40]:
#바교 연산자
x = np.array([1, 2, 3, 4, 5])
print( x < 3 )
print(np.less(x, 3))
print(x > 3)
print(np.greater(x, 3))
print(x <= 3)
print(np.less_equal(x, 3))
print(x == 3)
print(np.equal(x, 3))
print(x != 3)
print(np.not_equal(x, 3))

[ True  True False False False]
[ True  True False False False]
[False False False  True  True]
[False False False  True  True]
[ True  True  True False False]
[ True  True  True False False]
[False False  True False False]
[False False  True False False]
[ True  True False  True  True]
[ True  True False  True  True]


In [49]:
rainfall = pd.read_csv('https://raw.githubusercontent.com/SoongMoo/soldesk202108/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/Seattle2014.csv')
nprain = rainfall['PRCP']
inches = np.array(nprain) / 254 # series를  np배열 변환
print(inches)
# 강수량이 0.5이상인 날은 몇일이나 되나요?
print(np.sum(inches > 0.5))
# 강수량이 0.5에서 0.8 사이인 날은 몇일이나 되나요?
print(np.sum((inches >= 0.5) & (inches <= 0.8)))
# 강수량이 0.5보다 적게 오고 0.8보다 많이 온날은?
print(np.sum(~((inches >= 0.5) & (inches <= 0.8))))
print(np.sum((inches < 0.5) | (inches > 0.8)))

# 비가 안온 날은 몇일 일까요?
print(np.sum(inches == 0))
# 비가 온날은 몇일 입니까?
print(np.sum(inches != 0))

[0.         0.16141732 0.05905512 0.         0.         0.01181102
 0.48031496 0.38188976 0.22834646 0.16929134 0.83858268 0.05905512
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.01968504 0.         0.
 0.         0.         0.         0.3503937  0.8503937  0.
 0.09055118 0.07874016 0.         0.         0.         0.
 0.         0.         0.2007874  0.01968504 0.72047244 0.66929134
 0.18110236 0.07086614 0.37007874 0.46062992 1.03937008 0.57086614
 0.5984252  0.03937008 0.11811024 0.11023622 0.0984252  0.24015748
 0.51181102 0.01181102 0.         0.         0.         0.01968504
 0.7519685  0.42125984 0.6496063  1.83858268 0.11811024 0.
 1.27165354 0.16929134 0.74015748 0.         0.         0.01968504
 0.27165354 0.31889764 1.09055118 0.01181102 0.         0.01968504
 0.         0.         0.         0.         0.         0.16141732
 0.14173228 0.01181102 0.87007874 0.5511811  0.         0.
 0.         0.         0.0984252  0.       

In [52]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))
print(x)
x.sort()
print(x)

[1 2 3 4 5]
[2 1 4 3 5]
[1 2 3 4 5]


In [58]:
x = np.array([2, 1, 4, 3, 5]) 
idx = np.argsort(x)
print(idx)
print(x[idx])
print(x[[1 ,0 ,3 ,2 ,4]])
print(x) # 팬시 인덱싱
print(np.sort(x))

[1 0 3 2 4]
[1 2 3 4 5]
[1 2 3 4 5]
[2 1 4 3 5]
[1 2 3 4 5]


In [63]:
x = np.random.randint(0,10,(4,6))
print(x)
#행단위 정렬 :y축기준
print(np.sort(x))
print(np.sort(x, axis=1))
# 열 단위로 정렬
print(np.sort(x, axis=0)) # x축기준 : 열

[[4 8 1 8 1 5]
 [8 2 7 2 0 2]
 [8 7 7 9 6 1]
 [8 0 5 2 3 8]]
[[1 1 4 5 8 8]
 [0 2 2 2 7 8]
 [1 6 7 7 8 9]
 [0 2 3 5 8 8]]
[[4 0 1 2 0 1]
 [8 2 5 2 1 2]
 [8 7 7 8 3 5]
 [8 8 7 9 6 8]]


In [68]:
# 파티션 나누기
x = np.array([7, 2, 3, 1, 6, 5, 4])
# 순서 상관없이 작은 숫자 3개 뽑아 왼쪽에 정렬
print(np.partition(x,3))
# 순서 상관없이 큰 숫자 3개 뽑아 오른쪽에 정렬
print(np.partition(x,-3))    

[2 1 3 4 6 5 7]
[2 1 3 4 5 6 7]


In [73]:
y = np.random.randint(0,10,(4,6))
print(y)
print(np.partition(y,2, axis=0 ))
print(np.partition(y,2, axis=1 ))

[[6 3 3 9 4 8]
 [9 0 8 8 5 6]
 [4 0 7 0 4 4]
 [8 5 4 3 0 0]]
[[4 0 3 0 0 0]
 [6 0 4 3 4 4]
 [8 3 7 8 4 6]
 [9 5 8 9 5 8]]
[[3 3 4 9 6 8]
 [0 5 6 8 9 8]
 [0 0 4 7 4 4]
 [0 0 3 4 8 5]]


In [79]:
arr = np.array([1,2,3,4,5])
print(arr) # 
# [1 2 3 4 5] : 행
#  0 1 2 3 4
arr1  = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1)
import pandas as pd
ser = pd.Series([1,2,3,4,5])
print(ser) # 열
print(ser[0])
ser = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(ser)
print(ser['a'])
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
print(data)

[1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]
0    1
1    2
2    3
3    4
4    5
dtype: int64
1
a    1
b    2
c    3
d    4
e    5
dtype: int64
1
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [85]:
print(ser)
print(ser.keys())
print(list(ser.items()))
ser['a'] = 1000
print(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]
a    1000
b       2
c       3
d       4
e       5
dtype: int64


In [92]:
print(ser['a':'c']) # 명시적 index
print(ser[0:3]) # 암시적 index
# 비교
print(ser[(ser > 4)])
# 마스킹 : 논리
## 2 ~ 4
print(ser[(ser>=2) & (ser<=4)])
print(ser['a'])
print(ser['b'])
print(ser[['a','b']]) #팬시  index # Series로 출력

a    1000
b       2
c       3
dtype: int64
a    1000
b       2
c       3
dtype: int64
a    1000
e       5
dtype: int64
b    2
c    3
d    4
dtype: int64
1000
2
a    1000
b       2
dtype: int64


In [103]:
ser = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(ser)
print(ser['a'])
print(ser[0])
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5]) 
#                                        0  1  2
#indexing
print(data[1]) # 명시적 index
print(data.iloc[1]) #암시적 index
print(data.loc[1]) # 명시적 index
#slicing
print(data.loc[1:3])# 명시적 index
print(data.iloc[0:2]) #암시적 index
print(data[1:3]) # 암시적 index

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1
a
b
a
1    a
3    b
dtype: object
1    a
3    b
dtype: object
3    b
5    c
dtype: object


In [104]:
arr = np.array([1,2,3]) 
arr2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
# DataFrame : 다차원 배열 : 2차원 배열       
                                               # 행번호
data  = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data1 = pd.Series([0.1, 0.25, 0.8, 0.9], index=['a','b','c','d'])
data2 = pd.Series([0.2, 0.3, 0.5, 0.8], index=['a','b','c','d'])

df = pd.DataFrame({"data":data,"data1":data1,"data2":data2})
print(df)

   data  data1  data2
a  0.25   0.10    0.2
b  0.50   0.25    0.3
c  0.75   0.80    0.5
d  1.00   0.90    0.8


In [107]:
area = pd.Series({'a': 12121, 'b': 23232,'c': 343434, 'd': 55454, 'e': 45454})
pop = pd.Series({'a': 45456, 'b': 685675,'c': 573532, 'd': 353535, 'e': 35235})
df1 = pd.DataFrame({"area":area, "pop":pop})
print(df1)
print(df1['area'])
print(df1.area)

     area     pop
a   12121   45456
b   23232  685675
c  343434  573532
d   55454  353535
e   45454   35235
a     12121
b     23232
c    343434
d     55454
e     45454
Name: area, dtype: int64
a     12121
b     23232
c    343434
d     55454
e     45454
Name: area, dtype: int64


In [113]:
dic = {'a':1, 'b' : 2}
print(dic['a'])
dic['a'] = 3 
print(dic)
dic['c'] = 10
print(dic)

print(df1)
print(df1['area'])
print(df1['pop'])
print(df1['area'] / df1['pop'])
df1['density'] = df1['area'] / df1['pop']
print(df1)
print(df1.T)

1
{'a': 3, 'b': 2}
{'a': 3, 'b': 2, 'c': 10}
     area     pop   density
a   12121   45456  0.266653
b   23232  685675  0.033882
c  343434  573532  0.598805
d   55454  353535  0.156856
e   45454   35235  1.290024
a     12121
b     23232
c    343434
d     55454
e     45454
Name: area, dtype: int64
a     45456
b    685675
c    573532
d    353535
e     35235
Name: pop, dtype: int64
a    0.266653
b    0.033882
c    0.598805
d    0.156856
e    1.290024
dtype: float64
     area     pop   density
a   12121   45456  0.266653
b   23232  685675  0.033882
c  343434  573532  0.598805
d   55454  353535  0.156856
e   45454   35235  1.290024
                    a              b              c              d  \
area     12121.000000   23232.000000  343434.000000   55454.000000   
pop      45456.000000  685675.000000  573532.000000  353535.000000   
density      0.266653       0.033882       0.598805       0.156856   

                    e  
area     45454.000000  
pop      35235.000000  
density     

In [129]:
print(area)
print(area.keys())
print(area.values) # 1차원배열
print(df1)
print(df1.keys())
print(df1.values) # 2차원배열

# 12124 : 1.2124 * 10^4 : 1.2124 * e+4
print(df1.loc['a'])
print(df1.iloc[0])

a     12121
b     23232
c    343434
d     55454
e     45454
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[ 12121  23232 343434  55454  45454]
     area     pop   density
a   12121   45456  0.266653
b   23232  685675  0.033882
c  343434  573532  0.598805
d   55454  353535  0.156856
e   45454   35235  1.290024
Index(['area', 'pop', 'density'], dtype='object')
[[1.21210000e+04 4.54560000e+04 2.66653467e-01]
 [2.32320000e+04 6.85675000e+05 3.38819412e-02]
 [3.43434000e+05 5.73532000e+05 5.98805298e-01]
 [5.54540000e+04 3.53535000e+05 1.56855757e-01]
 [4.54540000e+04 3.52350000e+04 1.29002412e+00]]
area       12121.000000
pop        45456.000000
density        0.266653
Name: a, dtype: float64
area       12121.000000
pop        45456.000000
density        0.266653
Name: a, dtype: float64


a     12121
b     23232
c    343434
d     55454
e     45454
dtype: int64
a     12121
b     23232
c    343434
d     55454
e     45454
dtype: int64
